### ISSUE TITLE
CPU usage?

### ISSUE THREAD

**Issue by luckman212** [mogenson/ttyplot-rs#2]
Thanks for making this.

I compiled it successfully on macOS 10.15.6.

I was trying to use it to plot kernel memory usage over time, using this command:
```
if sudo -v; then while true; do \
  sudo zprint |\
  awk '$1~/^kalloc/ { sub("K","",$3); sum+=$3; } END { print sum; }'; \
  sleep 1; \
  done |\
  ploot; \
fi
```

I noticed my fans start to spin up like crazy so I checked Activity Monitor. I saw ploot using 99-100% CPU.

To rule out sudo, awk, zprint as possible culprits, I retried using a simple counter:
```
c=0; while true; do (( c++ )); echo $c; sleep 1; done | ploot
```
Same result. Any idea why this could be? Do I need to capture a spindump etc?

![image](https://user-images.githubusercontent.com/1992842/88199525-f891be00-cc12-11ea-9030-d07081e58472.png)

**Comment by mogenson** [comment]
The plotting thread polls both the piped stdin and tty for data or a CTRL-C signal instead of blocking on input. This is so you can exit the program while waiting on data. Unfortunately, this appears to result in high CPU usage.

I've set the main thread to sleep for a short time in commit 213a7f7. Let me know if this lowers your CPU usage.

In the future, I'll investigate an async framework, such as tokio.

**Comment by luckman212** [comment]
Thanks for looking at this. Just built a new binary and CPU usage is down to 1-2% now! 🎉
